wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1673851147
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 17
      4: 3.9.12
      5: 0.12.18
      8:
      - 5
config:
  desc: null
  value: {}
config_orig:
  desc: null
  value:
    config_type: ret
    cuda_non_blocking: true
    cudnn_benchmark: false
    cudnn_deterministic: true
    cudnn_enabled: true
    dataset_train:
      add_stop_frame: 1
      data_type: retrieval
      drop_last: false
      expand_segments: 10
      frames_noise: 0
      include_background: true
      max_clips: -1
      max_datapoints: -1
      max_frames: 80
      metadata_name: all
      min_clips: 1
      min_frames: 1
      name: activitynet
      num_workers: 5
      pin_memory: true
      preload_text_feat: false
      preload_vid_feat: false
      shuffle: true
      split: train
      subset: default
      text_feat_dim: 1536
      text_feat_name: text_feat_activitynet_meta_all_transformers_bert-base-uncased_-2,-1
      text_feat_source: h5
      text_preprocessing: bert_paper
      use_clips: true
      vid_feat_dim: 2048
      vid_feat_name: ICEP_V3_global_pool_skip_8_direct_resize
      vid_feat_source: npz_activitynet
      words_noise: 0
    dataset_val:
      num_workers: 5
      preload_text_feat: false
      preload_vid_feat: false
      same_as: dataset_train
      shuffle: false
      split: val_1
    description: activitynet with inception features.
    fp16_train: true
    fp16_val: true
    logging:
      step_gpu: -1
      step_gpu_once: 10
      step_train: 10
      step_val: 10
    lr_scheduler:
      name: reduce_opw
      rop_cooldown: 3
      rop_factor: 0.1
      rop_min_lr_factor: 0
      rop_patience: 2
      warmup_epochs: 3
      warmup_type: epoch
    net_text_global:
      same_as: net_video_global
    net_text_local:
      same_as: net_video_local
    net_video_global:
      crossatn_config:
        activation: gelu
        dropout: 0.025
        hidden_dim: 384
        norm: layernorm_coot
        num_heads: 8
        num_layers: 1
        pointwise_ff_dim: 384
      input_fc_config: null
      name: transformer
      output_dim: 768
      pooler_config:
        name: avg_special
      same_as: net_video_local
      use_context: true
      use_input_fc: false
    net_video_local:
      add_local_cls_token: false
      dropout_input: 0
      input_fc_config:
        activation_middle: none
        activation_output: gelu
        dropout_middle: 0
        dropout_output: 0
        hidden_dim: 0
        norm_middle: none
        norm_output: none
        num_layers: 1
        output_dim: 384
        residual: none
      name: transformer
      norm_input: layernorm_coot
      output_dim: 384
      pooler_config:
        activation: gelu
        dropout: 0.025
        hidden_dim: 768
        name: atn
        num_heads: 2
        num_layers: 1
      positional_encoding: sincos
      selfatn_config:
        activation: gelu
        dropout: 0.025
        hidden_dim: 384
        norm: layernorm_coot
        num_heads: 8
        num_layers: 1
        pointwise_ff_dim: 384
      use_context: false
      use_input_fc: true
      use_output_fc: false
      weight_init_std: 0.01
      weight_init_type: truncnorm
    optimizer:
      adam_amsgrad: false
      adam_beta2: 0.999
      adam_eps: 1.0e-08
      lr: 0.001
      lr_decay_mult: false
      momentum: 0.9
      name: adam
      radam_degentosgd: false
      sgd_nesterov: false
      weight_decay: 2.0e-05
      weight_decay_for_bias: true
    random_seed: 1001
    saving:
      keep_freq: -1
      save_best: true
      save_last: true
      save_opt_state: true
    train:
      batch_size: 64
      clip_gradient: -1
      contrastive_loss_config:
        margin: 0.2
        weight_context: 1.0
        weight_context_internal: 0.0
        weight_high: 1.0
        weight_high_internal: 1.0
        weight_low: 1.0
        weight_low_internal: 1.0
      loss_cycle_cons: 0.01
      loss_func: contrastive
      num_epochs: 100
    use_cuda: true
    use_multi_gpu: true
    val:
      batch_size: 64
      det_best_compare_mode: max
      det_best_field: val_score_at_1
      det_best_terminate_after: 16
      det_best_threshold_mode: rel
      det_best_threshold_value: 0.0001
      val_clips: false
      val_clips_freq: 1
      val_freq: 1
      val_start: 0
config_type:
  desc: null
  value: ret
cuda_non_blocking:
  desc: null
  value: true
cudnn_benchmark:
  desc: null
  value: false
cudnn_deterministic:
  desc: null
  value: true
cudnn_enabled:
  desc: null
  value: true
dataset_train:
  desc: null
  value: "\n---------- RetrievalDatasetConfig\n    name = activitynet\n    data_type\
    \ = retrieval\n    subset = default\n    split = train\n    max_datapoints = -1\n\
    \    shuffle = True\n    pin_memory = True\n    num_workers = 5\n    drop_last\
    \ = False\n    metadata_name = all\n    vid_feat_name = ICEP_V3_global_pool_skip_8_direct_resize\n\
    \    vid_feat_source = npz_activitynet\n    vid_feat_dim = 2048\n    text_feat_name\
    \ = text_feat_activitynet_meta_all_transformers_bert-base-uncased_-2,-1\n    text_feat_source\
    \ = h5\n    text_feat_dim = 1536\n    min_frames = 1\n    max_frames = 80\n  \
    \  use_clips = True\n    min_clips = 1\n    max_clips = -1\n    include_background\
    \ = True\n    add_stop_frame = 1\n    expand_segments = 10\n    frames_noise =\
    \ 0\n    words_noise = 0\n    text_preprocessing = bert_paper\n    preload_vid_feat\
    \ = False\n    preload_text_feat = False"
dataset_val:
  desc: null
  value: "\n---------- RetrievalDatasetConfig\n    name = activitynet\n    data_type\
    \ = retrieval\n    subset = default\n    split = val_1\n    max_datapoints = -1\n\
    \    shuffle = False\n    pin_memory = True\n    num_workers = 5\n    drop_last\
    \ = False\n    metadata_name = all\n    vid_feat_name = ICEP_V3_global_pool_skip_8_direct_resize\n\
    \    vid_feat_source = npz_activitynet\n    vid_feat_dim = 2048\n    text_feat_name\
    \ = text_feat_activitynet_meta_all_transformers_bert-base-uncased_-2,-1\n    text_feat_source\
    \ = h5\n    text_feat_dim = 1536\n    min_frames = 1\n    max_frames = 80\n  \
    \  use_clips = True\n    min_clips = 1\n    max_clips = -1\n    include_background\
    \ = True\n    add_stop_frame = 1\n    expand_segments = 10\n    frames_noise =\
    \ 0\n    words_noise = 0\n    text_preprocessing = bert_paper\n    preload_vid_feat\
    \ = False\n    preload_text_feat = False"
description:
  desc: null
  value: activitynet with inception features.
dim_feat_global:
  desc: null
  value: 768
dim_feat_local:
  desc: null
  value: 384
fp16_train:
  desc: null
  value: true
fp16_val:
  desc: null
  value: true
logging:
  desc: null
  value: "\n---------- BaseLoggingConfig\n    step_train = 10\n    step_val = 10\n\
    \    step_gpu = -1\n    step_gpu_once = 10"
lr_scheduler:
  desc: null
  value: "\n---------- SchedulerConfig\n    name = reduce_opw\n    warmup_type = epoch\n\
    \    warmup_epochs = 3\n    rop_factor = 0.1\n    rop_patience = 2\n    rop_cooldown\
    \ = 3\n    rop_min_lr_factor = 0"
model_cfgs:
  desc: null
  value:
    net_text_global: "\n---------- TransformerConfig\n    name = transformer\n   \
      \ output_dim = 768\n    dropout_input = 0\n    norm_input = layernorm_coot\n\
      \    positional_encoding = sincos\n    add_local_cls_token = False\n    use_input_fc\
      \ = False\n\n---------- TransformerEncoderConfig\n    hidden_dim = 384\n   \
      \ num_layers = 1\n    dropout = 0.025\n    num_heads = 8\n    pointwise_ff_dim\
      \ = 384\n\n---------- ActivationConfig\n    name = gelu\n    negative_slope\
      \ = 0.01\n\n---------- NormalizationConfig\n    name = layernorm_coot\n    eps\
      \ = 1e-06\n    affine = True\n    momentum = 0.1\n    track_running_stats =\
      \ True\n    use_output_fc = False\n    use_context = True\n\n---------- TransformerEncoderConfig\n\
      \    hidden_dim = 384\n    num_layers = 1\n    dropout = 0.025\n    num_heads\
      \ = 8\n    pointwise_ff_dim = 384\n\n---------- ActivationConfig\n    name =\
      \ gelu\n    negative_slope = 0.01\n\n---------- NormalizationConfig\n    name\
      \ = layernorm_coot\n    eps = 1e-06\n    affine = True\n    momentum = 0.1\n\
      \    track_running_stats = True\n\n---------- PoolerConfig\n    name = avg_special\n\
      \    hidden_dim = 0\n    num_heads = 1\n    num_layers = 1\n    dropout = 0\n\
      \n---------- ActivationConfig\n    name = relu\n    negative_slope = 0.01\n\
      \    weight_init_type = truncnorm\n    weight_init_std = 0.01\n    linear_out\
      \ = False"
    net_text_local: "\n---------- TransformerConfig\n    name = transformer\n    output_dim\
      \ = 384\n    dropout_input = 0\n    norm_input = layernorm_coot\n    positional_encoding\
      \ = sincos\n    add_local_cls_token = False\n    use_input_fc = True\n\n----------\
      \ MLPConfig\n    output_dim = 384\n    num_layers = 1\n    hidden_dim = 384\n\
      \n---------- ActivationConfig\n    name = none\n    negative_slope = 0.01\n\n\
      ---------- ActivationConfig\n    name = gelu\n    negative_slope = 0.01\n  \
      \  dropout_middle = 0\n    dropout_output = 0\n\n---------- NormalizationConfig\n\
      \    name = none\n    eps = 1e-06\n    affine = True\n    momentum = 0.1\n \
      \   track_running_stats = True\n\n---------- NormalizationConfig\n    name =\
      \ none\n    eps = 1e-06\n    affine = True\n    momentum = 0.1\n    track_running_stats\
      \ = True\n    residual = none\n\n---------- TransformerEncoderConfig\n    hidden_dim\
      \ = 384\n    num_layers = 1\n    dropout = 0.025\n    num_heads = 8\n    pointwise_ff_dim\
      \ = 384\n\n---------- ActivationConfig\n    name = gelu\n    negative_slope\
      \ = 0.01\n\n---------- NormalizationConfig\n    name = layernorm_coot\n    eps\
      \ = 1e-06\n    affine = True\n    momentum = 0.1\n    track_running_stats =\
      \ True\n    use_output_fc = False\n    use_context = False\n\n---------- PoolerConfig\n\
      \    name = atn\n    hidden_dim = 768\n    num_heads = 2\n    num_layers = 1\n\
      \    dropout = 0.025\n\n---------- ActivationConfig\n    name = gelu\n    negative_slope\
      \ = 0.01\n    weight_init_type = truncnorm\n    weight_init_std = 0.01\n   \
      \ linear_out = False"
    net_video_global: "\n---------- TransformerConfig\n    name = transformer\n  \
      \  output_dim = 768\n    dropout_input = 0\n    norm_input = layernorm_coot\n\
      \    positional_encoding = sincos\n    add_local_cls_token = False\n    use_input_fc\
      \ = False\n\n---------- TransformerEncoderConfig\n    hidden_dim = 384\n   \
      \ num_layers = 1\n    dropout = 0.025\n    num_heads = 8\n    pointwise_ff_dim\
      \ = 384\n\n---------- ActivationConfig\n    name = gelu\n    negative_slope\
      \ = 0.01\n\n---------- NormalizationConfig\n    name = layernorm_coot\n    eps\
      \ = 1e-06\n    affine = True\n    momentum = 0.1\n    track_running_stats =\
      \ True\n    use_output_fc = False\n    use_context = True\n\n---------- TransformerEncoderConfig\n\
      \    hidden_dim = 384\n    num_layers = 1\n    dropout = 0.025\n    num_heads\
      \ = 8\n    pointwise_ff_dim = 384\n\n---------- ActivationConfig\n    name =\
      \ gelu\n    negative_slope = 0.01\n\n---------- NormalizationConfig\n    name\
      \ = layernorm_coot\n    eps = 1e-06\n    affine = True\n    momentum = 0.1\n\
      \    track_running_stats = True\n\n---------- PoolerConfig\n    name = avg_special\n\
      \    hidden_dim = 0\n    num_heads = 1\n    num_layers = 1\n    dropout = 0\n\
      \n---------- ActivationConfig\n    name = relu\n    negative_slope = 0.01\n\
      \    weight_init_type = truncnorm\n    weight_init_std = 0.01\n    linear_out\
      \ = False"
    net_video_local: "\n---------- TransformerConfig\n    name = transformer\n   \
      \ output_dim = 384\n    dropout_input = 0\n    norm_input = layernorm_coot\n\
      \    positional_encoding = sincos\n    add_local_cls_token = False\n    use_input_fc\
      \ = True\n\n---------- MLPConfig\n    output_dim = 384\n    num_layers = 1\n\
      \    hidden_dim = 384\n\n---------- ActivationConfig\n    name = none\n    negative_slope\
      \ = 0.01\n\n---------- ActivationConfig\n    name = gelu\n    negative_slope\
      \ = 0.01\n    dropout_middle = 0\n    dropout_output = 0\n\n---------- NormalizationConfig\n\
      \    name = none\n    eps = 1e-06\n    affine = True\n    momentum = 0.1\n \
      \   track_running_stats = True\n\n---------- NormalizationConfig\n    name =\
      \ none\n    eps = 1e-06\n    affine = True\n    momentum = 0.1\n    track_running_stats\
      \ = True\n    residual = none\n\n---------- TransformerEncoderConfig\n    hidden_dim\
      \ = 384\n    num_layers = 1\n    dropout = 0.025\n    num_heads = 8\n    pointwise_ff_dim\
      \ = 384\n\n---------- ActivationConfig\n    name = gelu\n    negative_slope\
      \ = 0.01\n\n---------- NormalizationConfig\n    name = layernorm_coot\n    eps\
      \ = 1e-06\n    affine = True\n    momentum = 0.1\n    track_running_stats =\
      \ True\n    use_output_fc = False\n    use_context = False\n\n---------- PoolerConfig\n\
      \    name = atn\n    hidden_dim = 768\n    num_heads = 2\n    num_layers = 1\n\
      \    dropout = 0.025\n\n---------- ActivationConfig\n    name = gelu\n    negative_slope\
      \ = 0.01\n    weight_init_type = truncnorm\n    weight_init_std = 0.01\n   \
      \ linear_out = False"
name:
  desc: null
  value: config_ret
optimizer:
  desc: null
  value: "\n---------- OptimizerConfig\n    name = adam\n    lr = 0.001\n    weight_decay\
    \ = 2e-05\n    weight_decay_for_bias = True\n    momentum = 0.9\n    sgd_nesterov\
    \ = False\n    adam_beta2 = 0.999\n    adam_eps = 1e-08\n    adam_amsgrad = False\n\
    \    radam_degentosgd = False\n    lr_decay_mult = False"
random_seed:
  desc: null
  value: 1001
saving:
  desc: null
  value: "\n---------- BaseSavingConfig\n    keep_freq = -1\n    save_last = True\n\
    \    save_best = True\n    save_opt_state = True"
strict:
  desc: null
  value: true
train:
  desc: null
  value: "\n---------- RetrievalTrainConfig\n    batch_size = 64\n    num_epochs =\
    \ 100\n    loss_func = contrastive\n    clip_gradient = -1\n    loss_cycle_cons\
    \ = 0.01\n\n---------- ContrastiveLossConfig\n    margin = 0.2\n    weight_high\
    \ = 1.0\n    weight_high_internal = 1.0\n    weight_low = 1.0\n    weight_low_internal\
    \ = 1.0\n    weight_context = 1.0\n    weight_context_internal = 0.0"
use_cuda:
  desc: null
  value: true
use_multi_gpu:
  desc: null
  value: true
val:
  desc: null
  value: "\n---------- RetrievalValConfig\n    batch_size = 64\n    val_freq = 1\n\
    \    val_start = 0\n    det_best_field = val_score_at_1\n    det_best_compare_mode\
    \ = max\n    det_best_threshold_mode = rel\n    det_best_threshold_value = 0.0001\n\
    \    det_best_terminate_after = 16\n    val_clips = False\n    val_clips_freq\
    \ = 1"
