wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1673943509
    t:
      1:
      - 1
      - 55
      4: 3.8.5
      5: 0.12.16
      8:
      - 5
